export default function Home() {
  return (
    <main>
      <section className="section hero">
        <p className="badge">Pré-venda imobiliária · Indaiatuba/SP</p>
        <h1>Eduque o comprador antes do corretor entrar.</h1>
        <p className="heroText">Transforme contatos soltos em leads com contexto, prioridade e próximo passo. A pré-venda inteligente organiza a jornada inicial do comprador e entrega para a imobiliária informações úteis antes do atendimento humano.</p>
        <div className="actions"><a className="button primary" href="#contato">Agendar diagnóstico</a><a className="button secondary" href="#exemplo-lead">Ver exemplo de lead</a></div>
      </section>
      <section className="section gridTwo"><div><p className="eyebrow">Dor da imobiliária</p><h2>Lead sem contexto não é oportunidade. É custo operacional.</h2></div><div className="copy"><p>O corretor perde tempo explicando renda, entrada, FGTS, parcela, subsídio e documentação antes de saber se existe potencial real de compra.</p><strong>O problema não é apenas gerar lead. É saber qual lead merece o tempo do corretor.</strong></div></section>
      <section className="section dark"><p className="eyebrow light">Como funciona</p><h2>Um funil simples antes do atendimento comercial.</h2><div className="flow"><div className="flowItem"><span>01</span><p>Comprador acessa o simulador</p></div><div className="flowItem"><span>02</span><p>Informa renda, entrada, FGTS, bairro e interesse</p></div><div className="flowItem"><span>03</span><p>Recebe orientação inicial</p></div><div className="flowItem"><span>04</span><p>É classificado por maturidade e prioridade</p></div><div className="flowItem"><span>05</span><p>A imobiliária recebe um resumo útil</p></div><div className="flowItem"><span>06</span><p>O corretor atende com mais contexto</p></div></div></section>
      <section className="section leadExample" id="exemplo-lead"><div><p className="eyebrow">Exemplo prático</p><h2>Exemplo do que o corretor recebe.</h2><p className="subtle">A imobiliária não recebe apenas nome e telefone. Recebe contexto comercial para conduzir o próximo contato.</p></div><article className="leadCard"><div className="leadHeader"><div><span className="label">Lead</span><h3>Maria S.</h3></div><span className="priority">Prioridade morna</span></div><dl><div><dt>Renda familiar</dt><dd>R$ 4.800</dd></div><div><dt>Entrada disponível</dt><dd>R$ 18.000</dd></div><div><dt>FGTS</dt><dd>Sim</dd></div><div><dt>Bairros de interesse</dt><dd>Campo Bonito / Jardim João Pioli</dd></div><div><dt>Tipo de imóvel</dt><dd>Apartamento ou casa econômica</dd></div><div><dt>Maturidade</dt><dd>Orientada</dd></div><div><dt>Principal dúvida</dt><dd>Valor de entrada e documentação</dd></div><div><dt>Trava atual</dt><dd>Ainda não sabe se a parcela cabe no orçamento</dd></div><div className="wide"><dt>Próximo passo recomendado</dt><dd>Validar documentação e apresentar opções compatíveis</dd></div></dl></article></section>
      <section className="section gridTwo soft"><div><p className="eyebrow">IA aplicada</p><h2>IA como apoio ao processo, não como substituta do corretor.</h2></div><div className="copy"><p>A IA pode ajudar a organizar respostas, classificar leads, identificar dúvidas recorrentes, sugerir próximos passos e apoiar o follow-up.</p><p>O papel da solução não é substituir o corretor, mas fazer o comprador chegar mais preparado.</p></div></section>
      <section className="section gridTwo"><div><p className="eyebrow">Piloto de 30 dias</p><h2>Piloto controlado para validar qualidade do lead.</h2><p className="subtle">Carteira limitada, simulação simples, envio por WhatsApp ou planilha estruturada e relatório semanal.</p></div><div className="card"><ul className="checkList"><li>1 carteira inicial de imóveis</li><li>1 fluxo de simulação</li><li>1 canal de handoff para a imobiliária</li><li>classificação dos leads</li><li>relatório semanal</li></ul><p className="metric">Ao final de 30 dias, avaliamos se os leads chegaram com contexto suficiente para melhorar o atendimento, reduzir retrabalho e aumentar avanço para contato, visita ou proposta.</p></div></section>
      <section className="section notes"><div className="note"><h3>Privacidade e consentimento</h3><p>Os dados informados serão usados apenas para orientação inicial, diagnóstico comercial, qualificação do atendimento e continuidade da conversa. O compartilhamento de informações deve ocorrer mediante consentimento.</p></div><div className="note"><h3>Simulação financeira</h3><p>As simulações são estimativas. Aprovação, taxa, subsídio e enquadramento dependem de análise oficial do banco, documentação, regras vigentes e avaliação do imóvel.</p></div></section>
      <section className="section finalCta" id="contato"><p className="eyebrow light">Contato</p><h2>Quer testar uma pré-venda mais inteligente?</h2><p>Flávio Souza Barros · WhatsApp: +55 11 98762-7570 · E-mail: Flavio.barros@wiiprojects.com</p></section>
    </main>
  );
}
